package com.cms.hibernate.data.ent;

/**
 * SysDataoptions generated by MyEclipse Persistence Tools
 */

public class SysDataoptions implements java.io.Serializable {

	// Fields

	private Integer optId;

	private Integer optDataid;

	private String optName;

	private Integer optValue;

	private Integer optIsEdit;

	// Constructors

	/** default constructor */
	public SysDataoptions() {
	}

	/** full constructor */
	public SysDataoptions(Integer optDataid, String optName, Integer optValue,
			Integer optIsEdit) {
		this.optDataid = optDataid;
		this.optName = optName;
		this.optValue = optValue;
		this.optIsEdit = optIsEdit;
	}

	// Property accessors

	public Integer getOptId() {
		return this.optId;
	}

	public void setOptId(Integer optId) {
		this.optId = optId;
	}

	public Integer getOptDataid() {
		return this.optDataid;
	}

	public void setOptDataid(Integer optDataid) {
		this.optDataid = optDataid;
	}

	public String getOptName() {
		return this.optName;
	}

	public void setOptName(String optName) {
		this.optName = optName;
	}

	public Integer getOptValue() {
		return this.optValue;
	}

	public void setOptValue(Integer optValue) {
		this.optValue = optValue;
	}

	public Integer getOptIsEdit() {
		return this.optIsEdit;
	}

	public void setOptIsEdit(Integer optIsEdit) {
		this.optIsEdit = optIsEdit;
	}

}