/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cms.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.DynaActionForm;
import org.apache.struts.actions.DispatchAction;

import com.cms.hibernate.message.biz.IMessageBiz;
import com.cms.hibernate.message.biz.impl.MessageBizImpl;
import com.cms.hibernate.message.ent.SysMessage;

/** 
 * MyEclipse Struts
 * Creation date: 05-11-2009
 * 
 * XDoclet definition:
 * @struts.action path="/main/message" name="messageForm" parameter="oper" scope="request" validate="true"
 */
public class MessageAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
     IMessageBiz mbiz=null;
	public IMessageBiz getMbiz() {
		return mbiz;
	}
	public void setMbiz(IMessageBiz mbiz) {
		this.mbiz = mbiz;
	}
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward doSendMsg(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DynaActionForm mf = (DynaActionForm) form;// TODO Auto-generated method stub
		SysMessage sm=(SysMessage)mf.get("message");
		System.out.println("·¢ËÍÏûÏ¢");
		mbiz.sendMes(sm);
		return null;
	}
}