/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cms.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;
import org.apache.struts.action.DynaActionForm;
import org.apache.struts.actions.DispatchAction;

import com.cms.hibernate.user.biz.IUserBiz;
import com.cms.hibernate.user.ent.Users;

/** 
 * MyEclipse Struts
 * Creation date: 05-14-2009
 * 
 * XDoclet definition:
 * @struts.action path="/system/user" name="userForm" input="/form/user.jsp" parameter="oper" scope="request" validate="true"
 */
public class UserAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
    private IUserBiz ubiz=null;
	public IUserBiz getUbiz() {
		return ubiz;
	}
	public void setUbiz(IUserBiz ubiz) {
		this.ubiz = ubiz;
	}
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward doDeleteUser(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//DynaActionForm uf = (DynaActionForm) form;// TODO Auto-generated method stub
		int uId=Integer.parseInt(request.getParameter("uId"));
		Users u=new Users();
		u.setUId(uId);
		ubiz.delete(u);
		System.out.println("删除用户:"+uId);
		ActionMessages info=new ActionMessages();
		info.add("info",new ActionMessage("user.SucDelUser"));
		super.addErrors(request, info);
		return mapping.findForward("user_doManage");
	}
	
	public ActionForward doUpdateUser(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DynaActionForm uf = (DynaActionForm) form;// TODO Auto-generated method stub
		Users u=(Users)uf.get("users");
		ubiz.update(u);
		System.out.println("修改用户"+u.getURealname());
		ActionMessages info=new ActionMessages();
		info.add("info",new ActionMessage("user.SucUpdateUser"));
		super.addErrors(request, info);
		return mapping.findForward("user_doManage");
	}
	
	public ActionForward doAddUser(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DynaActionForm uf = (DynaActionForm) form;// TODO Auto-generated method stub
		Users u=(Users)uf.get("users");
		ubiz.insert(u);
		System.out.println("增加用户"+u.getURealname());
		ActionMessages info=new ActionMessages();
		info.add("info",new ActionMessage("user.SucAddUser"));
		super.addErrors(request, info);
		return mapping.findForward("user_doManage");
	}
}