/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cms.struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.cms.hibernate.customer.ent.Cusnote;
import com.cms.hibernate.customer.ent.Cusorder;
import com.cms.hibernate.customer.ent.Cusstaff;
import com.cms.hibernate.customer.ent.Customers;

/** 
 * MyEclipse Struts
 * Creation date: 04-27-2009
 * 
 * XDoclet definition:
 * @struts.form name="customerForm"
 */
public class CustomerForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** customers property */
	private Customers customers=new Customers();

	/** cusstaff property */
	private Cusstaff cusstaff=new Cusstaff();

	/** cusorder property */
	private Cusorder cusorder=new Cusorder();

	/** cusnote property */
	private Cusnote cusnote=new Cusnote();
	/*
	 * Generated Methods
	 */
	
	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public Cusnote getCusnote() {
		return cusnote;
	}

	public void setCusnote(Cusnote cusnote) {
		this.cusnote = cusnote;
	}

	public Cusorder getCusorder() {
		return cusorder;
	}

	public void setCusorder(Cusorder cusorder) {
		this.cusorder = cusorder;
	}

	public Cusstaff getCusstaff() {
		return cusstaff;
	}

	public void setCusstaff(Cusstaff cusstaff) {
		this.cusstaff = cusstaff;
	}

	public Customers getCustomers() {
		return customers;
	}

	public void setCustomers(Customers customers) {
		this.customers = customers;
	}
}