/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cms.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import com.cms.hibernate.data.ent.SysDataoptions;
import com.cms.hibernate.data.ent.SysDatas;

/** 
 * MyEclipse Struts
 * Creation date: 04-24-2009
 * 
 * XDoclet definition:
 * @struts.form name="dataForm"
 */
public class DataForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** datas property */
	private SysDatas datas=new SysDatas();

	/** options property */
	private SysDataoptions options=new SysDataoptions();

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the datas.
	 * @return SysDatas
	 */
	public SysDatas getDatas() {
		return datas;
	}

	/** 
	 * Set the datas.
	 * @param datas The datas to set
	 */
	public void setDatas(SysDatas datas) {
		this.datas = datas;
	}

	/** 
	 * Returns the options.
	 * @return SysDataoptions
	 */
	public SysDataoptions getOptions() {
		return options;
	}

	/** 
	 * Set the options.
	 * @param options The options to set
	 */
	public void setOptions(SysDataoptions options) {
		this.options = options;
	}
}