/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cms.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import com.cms.hibernate.customer.ent.Customers;
import com.cms.hibernate.services.ent.Services;

/** 
 * MyEclipse Struts
 * Creation date: 05-07-2009
 * 
 * XDoclet definition:
 * @struts.form name="servicesForm"
 */
public class ServicesForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** customer property */
	private Customers customer=new Customers();

	/** services property */
	private Services services=new Services();

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the customer.
	 * @return Customers
	 */
	public Customers getCustomer() {
		return customer;
	}

	/** 
	 * Set the customer.
	 * @param customer The customer to set
	 */
	public void setCustomer(Customers customer) {
		this.customer = customer;
	}

	/** 
	 * Returns the services.
	 * @return Services
	 */
	public Services getServices() {
		return services;
	}

	/** 
	 * Set the services.
	 * @param services The services to set
	 */
	public void setServices(Services services) {
		this.services = services;
	}
}