/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cms.struts.action;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;
import org.apache.struts.actions.DispatchAction;

import com.cms.hibernate.sell.biz.ISellChanceBiz;
import com.cms.hibernate.sell.biz.ISellPlanBiz;
import com.cms.hibernate.sell.biz.impl.SellChanceBizImpl;
import com.cms.hibernate.sell.biz.impl.SellPlanBizImpl;
import com.cms.hibernate.sell.ent.Sellchance;
import com.cms.hibernate.sell.ent.Sellplan;
import com.cms.struts.form.SellForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-28-2009
 * 
 * XDoclet definition:
 * @struts.action path="/sell" name="sellForm" parameter="oper" scope="request" validate="true"
 */
public class SellAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	
	private ISellChanceBiz chanceBiz=null;
	private ISellPlanBiz planBiz=null;
	
	
	
	public ISellChanceBiz getChanceBiz() {
		return chanceBiz;
	}

	public void setChanceBiz(ISellChanceBiz chanceBiz) {
		this.chanceBiz = chanceBiz;
	}

	public ISellPlanBiz getPlanBiz() {
		return planBiz;
	}

	public void setPlanBiz(ISellPlanBiz planBiz) {
		this.planBiz = planBiz;
	}

	public ActionForward doCreateChance(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
		SellForm sellForm = (SellForm) form;
		Sellchance chance=sellForm.getChance();
		
		System.out.print(chance.getChaCode());
		ActionMessages info=new ActionMessages();
		try{
		chanceBiz.newChance(chance);
		info.add("infoChance",new ActionMessage("sell.SucCreateChance"));
		}catch(Exception ex)
		{
	    info.add("infoChance",new ActionMessage("sell.FailCreateChance"));	
		}
		super.saveErrors(request, info);
		return mapping.findForward("sell_doCreateChance");
	}
	
	public ActionForward doEditChance(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
		SellForm sellForm = (SellForm) form;
		Sellchance chance=sellForm.getChance();
		System.out.print(chance.getChaCode());
		chanceBiz.editChance(chance);
		ActionMessages info=new ActionMessages();
		info.add("info", new ActionMessage("sell.SucOrderService"));
		super.addErrors(request, info);
		try {
			request.getRequestDispatcher("/sellManage/sell_doEditChance.jsp?chaID="+chance.getChaId()).forward(request, response);
			//response.sendRedirect("sell_doEditChance.jsp?chaID="+);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ServletException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return null;
		//return mapping.findForward("sell_doEditChance");
	}
	
	public ActionForward doOrderChance(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
		SellForm sellForm = (SellForm) form;
		Sellchance chance=sellForm.getChance();
		int chaid=chance.getChaId();
		System.out.print(chance.getChaCode());
		chance.setChaStaut(2);
		chanceBiz.orderChance(chance);
		ActionMessages info=new ActionMessages();
		info.add("info", new ActionMessage("sell.SucOrderService"));
		super.addErrors(request, info);
		try {
			request.getRequestDispatcher("/sellManage/sell_doOrderChance.jsp?chaID="+chaid).forward(request, response);
			//response.sendRedirect("sell_doOrderChance.jsp?chaID="+chance.getChaId());
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ServletException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return null;
		//return mapping.findForward("sell_doEditChance");
	}
	

	public ActionForward doDeleteChance(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
		//SellForm sellForm = (SellForm) form;
		int id=Integer.parseInt(request.getParameter("chaID"));
		chanceBiz.delete(id);
		ActionMessages info=new ActionMessages();
		info.add("info", new ActionMessage("sell.SucDelChance"));
		super.addMessages(request, info);
		return mapping.findForward("sell_showChance");
	}

	public ActionForward doEditPlan(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
		SellForm sellForm = (SellForm) form;
		Sellplan sp=sellForm.getPlan();
		Sellchance sc=sellForm.getChance();
		int chaid=sc.getChaId();
		planBiz.editPlan(sp);
		System.out.println("编辑计划");
		ActionMessages info=new ActionMessages();
		info.add("info", new ActionMessage("sell.SucEditPlan"));
		super.addErrors(request, info);
		try {
			request.getRequestDispatcher("/sellManage/sell_doAddPlan.jsp?chaID="+chaid).forward(request, response);
			//response.sendRedirect("sell_doAddPlan.jsp?chaID="+sc.getChaId());
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ServletException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return null;
	}
	
	public ActionForward doDeletePlan(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
		SellForm sellForm = (SellForm) form;
		planBiz.delete(sellForm.getPlan().getPlanId());
		Sellchance sc=sellForm.getChance();
		System.out.println("删除计划");
		ActionMessages info=new ActionMessages();
		info.add("info", new ActionMessage("sell.SucDelPlan"));
		super.addErrors(request, info);
		try {
			request.getRequestDispatcher("/sellManage/sell_doAddPlan.jsp?chaID="+sc.getChaId()).forward(request, response);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ServletException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return null;
	}
	
	public ActionForward doAddPlan(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
		SellForm sellForm = (SellForm) form;
		Sellplan sp=sellForm.getPlan();
		planBiz.addPlan(sp);
		int chaid=sp.getPlanChanceid();
		System.out.println("增加计划:"+sp.getPlanChanceid());
		ActionMessages info=new ActionMessages();
		info.add("info", new ActionMessage("sell.SucAddPlan"));
		super.addErrors(request, info);
			try {
				request.getRequestDispatcher("/sellManage/sell_doAddPlan.jsp?chaID="+chaid).forward(request, response);
			} catch (ServletException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
	
		return null;
	}
	
	
	public ActionForward doExectuePlan(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{ 
		SellForm sellForm = (SellForm) form;
		planBiz.executePlan(sellForm.getPlan());
		int chaid=sellForm.getChance().getChaId();
		ActionMessages info=new ActionMessages();
		info.add("info", new ActionMessage("sell.SucExcutePlan"));
		super.addErrors(request, info);
		try {
			request.getRequestDispatcher("/sellManage/sell_doExecutePlan.jsp?chaID="+chaid).forward(request, response);
		} catch (ServletException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}
		return null;
	}
	
	
	public ActionForward doChanceSuccess(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
		
		SellForm sellForm = (SellForm) form;
	    Sellchance cha=sellForm.getChance();
	    int chaid=Integer.parseInt(request.getParameter("chaID"));
	    cha.setChaId(chaid);
	    System.out.println("开发成功");
	    //cha.setChaStaut(3);
		chanceBiz.createCustomer(cha);
		ActionMessages info=new ActionMessages();
		info.add("info",new ActionMessage("sell.SucCreateCustomer"));
		super.addErrors(request, info);
		return mapping.findForward("sell_showEmpolder");
	}
	
	public ActionForward doChanceFile(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
		SellForm sellForm = (SellForm) form;
	    Sellchance cha=sellForm.getChance();
		int chaid=Integer.parseInt(request.getParameter("chaID"));
	    cha.setChaId(chaid);
	    chanceBiz.doChanceFile(cha);
	    System.out.println("归档成功");
	    ActionMessages info=new ActionMessages();
		info.add("info",new ActionMessage("sell.SucChanceFile"));
		super.addErrors(request, info);
		return mapping.findForward("sell_showEmpolder");
	}
	
	public ActionForward searchChance(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
		String url=request.getParameter("url");
		SellForm sf = (SellForm) form;
		Sellchance sc=sf.getChance();
		List list=chanceBiz.search(sc, 0, 0);
		if(list!=null)
		request.setAttribute("list", list);
		else
	     request.setAttribute("list", new ArrayList());
		return mapping.findForward(url);
	}

	
}